Fixed pom conf bug. We had an older version of datanucleus-core and a method was not there. So we got the exception: 'Caused by: java.lang.NoSuchMethodError: org.datanucleus.metadata.MetaDataManager.setAllowXML(Z)V'